# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.90

[window.padding]
x = 7
y = 0
